"""FND-002A: generate the fact file that documentation must cite.

`docs/COMMERCIAL_ROADMAP.md` still refers to tests that were deleted and to
course statistics that no longer hold. That is how a project ends up believing
its own outdated claims. The rule the plan sets is simple: any number that
appears in the documentation — test counts, segment counts, quality status —
comes from this generated file, and this file is generated by measuring, never
by hand.

    python src/implementation_facts.py

Writes `implementation-facts.json` at the project root.
"""

from __future__ import annotations

import json
import subprocess
import sys
import unittest
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PROJECT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_DIR / "src"))

from bundle_quality import audit_manifest  # noqa: E402
from exam_schema import audit_exam, iter_questions  # noqa: E402
from lexicon_schema import audit_pack  # noqa: E402


def count_python_tests() -> int:
    sys.path.insert(0, str(PROJECT_DIR / "tests"))
    suite = unittest.defaultTestLoader.discover(str(PROJECT_DIR / "tests"), pattern="test_*.py")
    return suite.countTestCases()


def count_node_tests() -> int | None:
    """Count node:test cases by running them and reading the summary."""
    try:
        completed = subprocess.run(
            ["node", "--test", "--test-reporter=tap", "tests/*.test.mjs"],
            cwd=PROJECT_DIR,
            capture_output=True,
            text=True,
            # Node writes UTF-8. Without this, `text=True` decodes with the console
            # codepage — GBK on a Simplified Chinese Windows — and a Japanese test name
            # anywhere in the TAP stream makes counting the tests raise instead of
            # returning a number.
            encoding="utf-8",
            errors="replace",
            timeout=120,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if completed.stdout is None:
        return None
    for line in completed.stdout.splitlines():
        if line.startswith("# pass "):
            return int(line.split()[-1])
    return None


def course_facts() -> list[dict[str, Any]]:
    facts = []
    for manifest_path in sorted((PROJECT_DIR / "courses").glob("*/manifest.json")):
        manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
        report = audit_manifest(manifest, require_enrichment=True)
        review = manifest.get("review") or {}
        facts.append(
            {
                "path": manifest_path.relative_to(PROJECT_DIR).as_posix(),
                "courseId": manifest.get("courseId"),
                "contentRevision": manifest.get("contentRevision"),
                "segments": len(manifest.get("sentences") or []),
                "practiceEligible": sum(
                    1 for s in manifest.get("sentences") or [] if s.get("practiceEligible")
                ),
                "qualityStatus": report["status"],
                "errors": report["summary"]["errors"],
                "warnings": report["summary"]["warnings"],
                "humanListening": review.get("humanListening"),
                "commercialRights": review.get("commercialRights"),
                # The gate in serve_course.py refuses any course with errors,
                # so this is the same predicate the launcher applies.
                "opensInPlayer": report["summary"]["errors"] == 0,
            }
        )
    return facts


def exam_facts() -> list[dict[str, Any]]:
    """Measure the JLPT question bank the same way courses are measured."""
    facts = []
    for exam_path in sorted((PROJECT_DIR / "exams").glob("*/exam.json")):
        exam = json.loads(exam_path.read_text(encoding="utf-8-sig"))
        report = audit_exam(exam)
        scored = [
            question for _, _, question in iter_questions(exam) if not question.get("example")
        ]
        facts.append(
            {
                "path": exam_path.relative_to(PROJECT_DIR).as_posix(),
                "examId": exam.get("examId"),
                "level": exam.get("level"),
                "sessionLabel": exam.get("sessionLabel"),
                "contentRevision": exam.get("contentRevision"),
                "questions": exam.get("questionCount"),
                "scoredQuestions": len(scored),
                "totalPoints": exam.get("totalPoints"),
                "sections": [
                    {
                        "title": section.get("title"),
                        "questions": section.get("questionCount"),
                        "audioRequired": section.get("audioRequired"),
                    }
                    for section in exam.get("sections") or []
                ],
                "qualityStatus": report["status"],
                "errors": report["summary"]["errors"],
                "warnings": report["summary"]["warnings"],
                # The gate in exam_store.py refuses any exam with errors, so this is
                # the same predicate the page applies.
                "opensInPlayer": report["summary"]["errors"] == 0,
            }
        )
    return facts


def lexicon_facts() -> dict[str, Any]:
    """Measure the vocabulary / grammar packs, including the ones not yet assembled.

    A pack directory with pages but no ``pack.json`` is the normal mid-pipeline state,
    not an error, and it is the state worth reporting: it says extraction ran and the
    human step has not. Reporting only assembled packs would make an in-progress import
    look like an absent one.
    """
    packs = []
    for directory in sorted((PROJECT_DIR / "lexicon").glob("*/")):
        meta_path = directory / "pack-meta.json"
        if not meta_path.is_file():
            continue
        meta = json.loads(meta_path.read_text(encoding="utf-8-sig"))
        pages = sorted(directory.glob("pages/p*.json"))
        issues = {"error": 0, "warning": 0}
        entry_blocks = 0
        for page_path in pages:
            page = json.loads(page_path.read_text(encoding="utf-8"))
            entry_blocks += sum(
                1 for block in page.get("blocks") or [] if block.get("type") == "entry"
            )
            for issue in page.get("issues") or []:
                severity = str(issue.get("severity"))
                if severity in issues:
                    issues[severity] += 1

        record: dict[str, Any] = {
            "path": directory.relative_to(PROJECT_DIR).as_posix().rstrip("/"),
            "packId": meta.get("packId"),
            "kind": meta.get("kind"),
            "level": meta.get("level"),
            "redistributable": (meta.get("attribution") or {}).get("redistributable"),
            "extractedPages": len(pages),
            "extractedEntryBlocks": entry_blocks,
            "extractIssues": issues,
            "assembled": False,
        }

        pack_path = directory / "pack.json"
        if pack_path.is_file():
            pack = json.loads(pack_path.read_text(encoding="utf-8-sig"))
            report = audit_pack(pack)
            record.update(
                {
                    "assembled": True,
                    "contentRevision": pack.get("contentRevision"),
                    "entries": pack.get("entryCount"),
                    "units": pack.get("unitCount"),
                    "cards": pack.get("cardCount"),
                    "qualityStatus": report["status"],
                    "errors": report["summary"]["errors"],
                    "warnings": report["summary"]["warnings"],
                    # The gate in lexicon_store.py refuses any pack with errors, so this
                    # is the same predicate the page applies.
                    "opensInWorkspace": report["summary"]["errors"] == 0,
                }
            )
        packs.append(record)
    return {"packs": packs}


def git_facts() -> dict[str, Any]:
    def git(*args: str) -> str | None:
        try:
            return subprocess.run(
                ["git", *args], cwd=PROJECT_DIR, capture_output=True, text=True, timeout=15
            ).stdout.strip() or None
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return None

    return {
        "isRepository": (PROJECT_DIR / ".git").is_dir(),
        "head": git("rev-parse", "--short", "HEAD"),
        "commitCount": git("rev-list", "--count", "HEAD"),
    }


def build_facts() -> dict[str, Any]:
    node_tests = count_node_tests()
    python_tests = count_python_tests()
    return {
        "schemaVersion": "implementation-facts-v1",
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "generatedBy": "src/implementation_facts.py",
        "note": "Generated by measurement. Do not hand-edit; do not cite numbers not present here.",
        "tests": {
            "pythonTests": python_tests,
            "nodeTests": node_tests,
            "total": python_tests + (node_tests or 0),
            "entryPoint": "python run_tests.py",
            "nodeAvailable": node_tests is not None,
        },
        "courses": course_facts(),
        "exams": exam_facts(),
        "lexicon": lexicon_facts(),
        "git": git_facts(),
    }


def main() -> int:
    facts = build_facts()
    target = PROJECT_DIR / "implementation-facts.json"
    target.write_text(json.dumps(facts, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    tests = facts["tests"]
    print(f"wrote {target.name}")
    print(f"  tests   : {tests['pythonTests']} python + {tests['nodeTests']} node = {tests['total']}")
    for exam in facts["exams"]:
        print(
            f"  exam    : {exam['path']} — {exam['scoredQuestions']} scored questions, "
            f"{exam['totalPoints']} points, {exam['qualityStatus']}"
        )
    for course in facts["courses"]:
        print(
            f"  course  : {course['path']} -> {course['qualityStatus']} "
            f"({course['errors']}e/{course['warnings']}w, {course['segments']} segments, "
            f"opens={course['opensInPlayer']})"
        )
    print(f"  git     : {facts['git']['head']} ({facts['git']['commitCount']} commits)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
